version: "3"

services:
  infrared:
    build: "."
    container_name: "infrared"
    restart: "unless-stopped"
    ports:
      - "25565:25565/tcp"
    volumes:
      - "/usr/local/infrared/configs:/configs"
    expose:
      - "25565"
